.github/dependabot.yml

Motivation ~ Need to add dependabot yml file for security 
Actions ~ Added dependabot.yml file

chore: add dependabot file

---

vite.config.ts

Motivation ~ not getting typescript suggestion in consumer projects
Actions ~ Added tsconfig.app.json to vite plugin

fix: add tsconfig plugin to vite

---

package.json

chore: add main and files in package json

---

package.json
vite.config.ts

chore: add main path

---

src/context/auth-context.tsx
src/main.tsx

chore: add logout ws call in context

---

package-lock.json
package.json
src/context/auth-context.tsx
src/main.tsx
vite.config.ts

chore: remove tanstack

---

src/context/index.ts
src/context/use-oauth2.ts
src/hooks/index.ts
src/hooks/useOAuth2.ts
src/index.ts

chore: add useoauth2 hook

---

src/hooks/useOAuth2.ts

chore: add sandbox

---

src/hooks/useOAuth2.ts

Added logs to debug origin issue with logout

---

src/hooks/useOAuth2.ts

Removed console logs and await logout function

---

src/hooks/useOAuth2.ts

chore: remove await

---

package-lock.json
package.json

chore: add react and dom to dev dependency

---

src/hooks/useOAuth2.ts

chore: event origin

---

src/hooks/useOAuth2.ts

chore: event check

---

src/hooks/useOAuth2.ts

chore: refactor onMessage

---

README.md
package-lock.json
package.json
src/index.ts
src/oidc/index.ts

The existing authentication flow required improvements to enhance security, ensure compatibility with modern OIDC standards, and simplify the token management process
1. Implemented OIDC configuration fetching: Added a function to dynamically fetch OIDC configuration endpoints from the provider’s well-known configuration endpoint and store them in local storage.
2. Authentication flow with UserManager: Utilized the UserManager class from oidc-client-ts to initiate the OIDC login flow, handling authorization, token exchange, and session management.
3. Redirection after authentication: Configured redirect_uri to ensure users are correctly redirected back to the application after successful authentication.
-   [x] New feature …

Thisyahlen/export OIDC functions

---

README.md
src/oidc/index.ts

- Added functions to integrate the OIDC access token retrieval flow and legacy token flow
-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

Adrienne / Added OIDC token and legacy token flow

---

package-lock.json
package.json

Fix build issue with rollup

---

.github/workflows/build.yml
package-lock.json
package.json
src/components/Callback/Callback.tsx
vite.config.ts

Fix styles build issue, added workflow to build and test on pull request, added extra prop to render custom button

---

.github/workflows/build.yml
package-lock.json
package.json

Fix build workflow and regenerate package lock

---

src/hooks/useOAuth2.ts

chore: add PostMessage on logout

---

package-lock.json
package.json
src/components/Callback/Callback.tsx
src/hooks/useOAuth2.ts

chore: add cookie to login and logout function

---

.github/workflows/coveralls.yml
babel.config.cjs
jest.config.cjs
package-lock.json
package.json
src/constants/__tests__/urls.spec.ts
src/oidc/__tests__/index.spec.ts

chore: add test setup

---

README.md

chore: add readme markdown

---

.github/workflows/build.yml

- For security steps, added verify user workflow to the build and test workflow

Added verify user step for build workflow

---

.gitignore
package-lock.json
package.json
src/constants/__tests__/urls.spec.ts
src/hooks/__tests__/useIsOAuth2Enabled.spec.ts
src/hooks/__tests__/useOAuth2.spec.ts

1. Generate unit test for useIsOauth2Enabled and useOauth2 hook.

chore: add test for hooks

---

src/components/Callback/Callback.tsx
src/hooks/__tests__/useOAuth2.spec.ts
src/hooks/useOAuth2.ts

chore: add cookie domain setter

---

package-lock.json
package.json

chore: revert semantic release version to fix release build

---

package-lock.json
package.json

chore: bump deriv utils

---

package-lock.json
package.json

chore: move testing library to dev dependency

---

src/components/Callback/Callback.scss

chore: add background to callback

---

src/oidc/oidc.ts

Adrienne / Issue with caching configuration

---

src/oidc/oidc.ts

chore: update oauth url

---

src/oidc/oidc.ts

chore: swap logout uri logic

---

src/oidc/oidc.ts

Added front-channel logout functionality

---

src/constants/__tests__/urls.spec.ts
src/oidc/oidc.ts

Fix logout redirect uri wrong url reconstruction

---

README.md
src/components/Callback/Callback.tsx
src/hooks/useOAuth2.ts
src/oidc/oidc.ts

- - Added `state` parameter so that additional metadata or payload can be passed over to the Callback page
-   [x] New feature (non-breaking change which adds functionality)

Add state parameter and whitelist deriv.dev for cookies

---

src/components/Callback/Callback.tsx
src/oidc/oidc.ts

-   [x] Bug fix (non-breaking change which fixes an issue)

Adrienne / Fix user state not being shown, made logout params optional

---

src/oidc/oidc.ts

-   [x] New feature (non-breaking change which adds functionality)

Adrienne / Add login_code parameter

---

README.md

amam/release auth client 1.4.6

---

src/index.ts
src/tmb/index.ts

Add TMB Exports
